# Generated by Django 2.1.2 on 2018-10-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=4)),
                ('ChName', models.CharField(max_length=20)),
                ('begin_date', models.CharField(max_length=8)),
                ('end_date', models.CharField(max_length=8)),
                ('rent_amt', models.IntegerField(default=0)),
            ],
        ),
    ]
