# Generated by Django 2.1.2 on 2018-10-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtsf01',
            name='PUB_DASHBOARD',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
