# Generated by Django 2.1.2 on 2018-10-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='begin_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.CharField(max_length=10),
        ),
    ]
